### ISSUE TITLE
PHP < 5.6 compatibility?

### ISSUE THREAD

**Issue by shesek** [ElementsProject/lightning-strike-client-php#1]

**Comment by shesek** [comment]
Related: https://github.com/ElementsProject/woocommerce-gateway-lightning/issues/7

**Comment by shesek** [comment]
It appears like PHP 5.6 already is compatible, its only PHP < 5.6 that isn't.

**Comment by analogic** [comment]
PHP < 5.6 is not officialy supported, anyone running payment gateway should not be running that old PHP anyway...

Btw. I've forked this client for more php7 awesomeness (https://github.com/analogic/lightning-charge-client-php7). I've tried develop on lnd but due cool features like grpc, macroons, certs it is seriously hard to develop simple php client without huge dependencies... Awesome work!

**Comment by shesek** [comment]
Very cool! I'm somewhat tempted to just make yours the official, but its probably still too early to depend on PHP 7, huh? :)

Regarding this ticket: you're probably right. I'll close it and revisit if anyone ever asks for it.

Cheers!

**Comment by analogic** [comment]
7+ is stable and very well working in production but my "patch" is more for programmers which especialy likes php7 features. It is not for general public as there is lot of code still running on 5.6. I would give it two years and then merge :)
